# Site settings
title: Predicto
email: predicto.live@outlook.com
url: https://skohari.github.io
description: "predicto.live is a suite of applications for data-manipulation, predictive model development and model validation.
  "

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#add8e6'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/predicto.live
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
