# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: predicto.live
            image:
        nav:
            - item_name: Solutions
              item_url: '#'
            - item_name: About Us
              item_url: '#'
            - item_name: Login (Members)
              item_url: '#'
    footer:
        content:
            logo:
                text: predicto.live
                image:
            copyright: Copyright &copy; 2020. - predicto.live <br>All rights reserved.
        social_list:
            - network_name: skype
              profile_url: 'skype:predicto.live?chat'
#             - network_name: twitter
#               profile_url: '#'
#             - network_name: instagram
#               profile_url: '#'
#             - network_name: youtube
#               profile_url: '#'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
